jogos/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, ValidationError


class NovoJogoForm(FlaskForm):

    rodada = IntegerField('Rodada', validators=[DataRequired()])
    data = DateField('Data da Partida')
    vermelhos_mandante = IntegerField('Vermelhos', default=0)
    mandante = SelectField('Time Mandante', coerce=int)
    gols_mandante = IntegerField('Gols')
    amarelos_mandante = IntegerField('Amarelos', default=0)
    visitante = SelectField('Time Visitante', coerce=int)
    gols_visitante = IntegerField('Gols')
    amarelos_visitante = IntegerField('Amarelos', default=0)
    vermelhos_visitante = IntegerField('Vermelhos', default=0)
    enviar = SubmitField('Enviar')

    def validate_visitante(self, visitante):
        if visitante.data == self.mandante.data:
            raise ValidationError('O Time mandante e o Visitante não podem'
                                  'ser o mesmo')

    def validate_rodada(self, rodada):
        if rodada.data > 10 or rodada.data < 0:
            raise ValidationError('Rodada Inválida')

jogos/__init__.py
from flask import Blueprint

bp = Blueprint('jogos', __name__, template_folder='./templates')

from jogos import routes

jogos/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required
from jogos import bp
from jogos.forms import NovoJogoForm
from models import Jogo, Time
from brasileirao import db
from sqlalchemy.exc import IntegrityError


@bp.route('/')
@login_required
def index():
    jogos = Jogo.jogos_rodada()
    return render_template('listarjogos.html', title='Jogos', jogos=jogos)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    form = NovoJogoForm()
    times = list(Time.query.with_entities(Time.id, Time.nome))
    form.mandante.choices = times
    form.visitante.choices = times
    if form.validate_on_submit():
        jogo = Jogo(rodada=form.rodada.data, data=form.data.data,
                    time_mandante_id=form.mandante.data,
                    gols_mandante=form.gols_mandante.data,
                    amarelos_mandante=form.amarelos_mandante.data,
                    vermelhos_mandante=form.vermelhos_mandante.data,
                    time_visitante_id=form.visitante.data,
                    gols_visitante=form.gols_visitante.data,
                    amarelos_visitante=form.amarelos_visitante.data,
                    vermelhos_visitante=form.vermelhos_visitante.data)
        try:
            db.session.add(jogo)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            e = {'Duplicidade': ["Esta partida já ocorrreu"]}
            return render_template('novojogo.html', title='Novo Jogo',
                                   form=form, jogo=None, errors=e)
        else:
            return redirect(url_for('jogos.index'))
    return render_template('novojogo.html', title='Novo Jogo', form=form,
                           jogo=None, errors=form.errors)


@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def update(id):
    jogo = Jogo.query.get_or_404(id)
    form = NovoJogoForm()
    times = list(Time.query.with_entities(Time.id, Time.nome))
    form.mandante.choices = times
    form.visitante.choices = times
    if form.validate_on_submit():
        jogo.rodada = form.rodada.data
        jogo.data = form.data.data
        jogo.time_mandante_id = form.mandante.data
        jogo.gols_mandante = form.gols_mandante.data
        jogo.amarelos_mandante = form.amarelos_mandante.data
        jogo.vermelhos_mandante = form.vermelhos_mandante.data
        jogo.time_visitante_id = form.visitante.data
        jogo.gols_visitante = form.gols_visitante.data
        jogo.amarelos_visitante = form.amarelos_visitante.data
        jogo.vermelhos_visitante = form.vermelhos_visitante.data
        db.session.add(jogo)
        db.session.commit()
        flash('Sua mudança foi salva')
        return redirect(url_for('jogos.index'))
    elif request.method == 'GET':
        form.rodada.data = jogo.rodada
        form.data.data = jogo.data
        form.mandante.data = jogo.time_mandante_id
        form.gols_mandante.data = jogo.gols_mandante
        form.amarelos_mandante.data = jogo.amarelos_mandante
        form.vermelhos_mandante.data = jogo.vermelhos_mandante
        form.visitante.data = jogo.time_visitante_id
        form.gols_visitante.data = jogo.gols_visitante
        form.amarelos_visitante.data = jogo.amarelos_visitante
        form.vermelhos_visitante.data = jogo.vermelhos_visitante
    return render_template('novojogo.html', form=form, title="Editar Jogo",
                           jogo=jogo, errors=form.errors)


@bp.route('/<int:id>/delete')
@login_required
def delete(id):
    jogo = Jogo.query.get_or_404(id)
    db.session.delete(jogo)
    db.session.commit()
    return redirect(url_for('jogos.index'))

jogos/templates/listarjogos.html
{% extends "base.html"%}

{% block app_content %}
<a href="{{ url_for('jogos.create') }}" class="btn btn-default">Novo Jogo</a>
<br>
<br>
<ul>
    {% for rodada in jogos %}
        <table class="table table-striped">
            <caption><h1>RODADA {{rodada }}</h1></caption>
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Mandante</th>
                    <th>Gols</th>
                    <th>X</th>
                    <th>Gols</th>
                    <th>Visitante</th>
                </tr>
            </thead>
            <tbody>       
            {% for jogo in jogos[rodada] %}
            <tr>
                <th>{{jogo.data.strftime('%d/%m/%Y') }}</th>
                <th>{{jogo.mandante.nome}}</th>
                <th>{{jogo.gols_mandante}}</th>
                <th>X</th>
                <th>{{jogo.gols_visitante}}</th>
                <th>{{jogo.visitante.nome}}</th>
                <th><a href="{{ url_for('jogos.update', id=jogo.id) }}" class="btn btn-default">editar</a></th>
                <th><a href="{{ url_for('jogos.delete', id=jogo.id) }}" class="btn btn-default">deletar</a></th>
            </tr>
            {% else %}   
            <div>Não houveram jogos para essa rodada</div>
            {% endfor %}    
            {% endfor %}    
</ul>

{% endblock %}

jogos/templates/novojogo.html
{% extends "base.html" %}


{% block app_content %}
<!-- Esse bloco é um gerenciamento de Erro, não precisa mexer -->
{% if errors %}
	<div class="container">
    	{%- for msg in errors %}
    		<div class="alert alert-danger" role="alert">
				{{ msg }}
				{% for error in errors[msg] %}
				{{error}}
				{% endfor %}
			</div>
    	{% endfor -%}
	</div>
{% endif %}
<!-- Faça o template a partir daqui-->

<h1> {{ title }}</h1>

<form action="" method="POST" novalidate>
	{{ form.hidden_tag() }}
	<div class="container">
	<div class="row">
		<div class="col-md-4">
			{{ form.rodada.label }} {{ form.rodada(size=12) }}<br>
			{{ form.data.label }} {{ form.data(size=27) }}<br>
			{{ form.mandante.label }} {{ form.mandante(size=1) }}<br>
			{{ form.gols_mandante.label }} {{ form.gols_mandante(size=7) }}<br>
			{{ form.amarelos_mandante.label }} {{ form.amarelos_mandante(size=8) }}<br>
			{{ form.vermelhos_mandante.label }} {{ form.vermelhos_mandante(size=7) }}<br>
			{{ form.visitante.label }} {{ form.visitante(size=1) }}<br>
			{{ form.gols_visitante.label }} {{ form.gols_visitante(size=7) }}<br>
			{{ form.amarelos_visitante.label }} {{ form.amarelos_visitante(size=8) }}<br>
			{{ form.vermelhos_visitante.label }} {{ form.vermelhos_visitante(size=7) }}<br>
			{{ form.enviar() }}
		</div>
	</div>
</div>
</form>

{% endblock %}